spring.profiles.active=dev
spring.application.name=todolist
spring.output.ansi.enable=ALWAYS

spring.datasource.driver-class-name=org.postgresql.Driver

server.error.include-exception=true

jwt.secret=${JWT_SECRET:oO5gyh37pVnHSmJBB5OfK9uSOuZgjxZfMRmZTE45xXdRAHc9s96l6ko2EboUEvs}
jwt.expiration=${JWT_EXPIRATION:86400000}